name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Triggers build when files are updated on your main branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20

      - name: Install Dependencies
        run: npm install

      - name: Build React Production App
        run: npm run build

      - name: Deploy Compiled Files to gh-pages Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite compiles everything into the 'dist' folder
          branch: gh-pages # Deploys automatically to this deployment branch
